# Generated by Django 5.2.7 on 2025-10-27 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم السورة')),
                ('nameWithoutTashkeel', models.CharField(max_length=30, verbose_name='اسم السورة بدون تشكيل')),
            ],
            options={
                'verbose_name': 'سورة',
                'verbose_name_plural': 'السور',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Verses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse_pk', models.CharField(max_length=8, unique=True, verbose_name='مفتاح الآية')),
                ('page', models.PositiveIntegerField(verbose_name='الصفحة')),
                ('hizbQuarter', models.PositiveIntegerField(verbose_name='الربع')),
                ('juz', models.PositiveIntegerField(verbose_name='الجزء')),
                ('verse', models.CharField(max_length=5000, verbose_name='الآية')),
                ('verseWithoutTashkeel', models.CharField(max_length=1000, verbose_name='الآية بدون تشكيل')),
                ('numberInSurah', models.PositiveIntegerField(verbose_name='رقم الآية في السورة')),
                ('numberInQuran', models.PositiveIntegerField(unique=True, verbose_name='رقم الآية في القرءان')),
                ('audio', models.URLField(unique=True, verbose_name='مصدر تلاوة أساسي')),
                ('audio1', models.URLField(blank=True, null=True, unique=True, verbose_name='مصدر تلاوة ثانوي 1')),
                ('audio2', models.URLField(blank=True, null=True, unique=True, verbose_name='مصدر تلاوة ثانوي 2')),
                ('sajda', models.BooleanField(verbose_name='هل الآية تحتوي علي سجدة')),
                ('surah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surah', to='search.surah', verbose_name='السورة')),
            ],
            options={
                'verbose_name': 'آية',
                'verbose_name_plural': 'الآيات',
                'ordering': ['id'],
            },
        ),
    ]
